name: Crash Report
description: Self Explanatory.
labels: [ "unverified", "crash" ]
body:
  - type: checkboxes
    attributes:
      label: Issue
      description: |
        When submitting a crash report, please make sure it's a crash report.
        Failing to do this will get your issue *closed without explanation*.
      options:
        - label: I confirm that this bug is NOT an issue with the GD Mega Overlay code.
          required: true
  - type: dropdown
    id: platform
    attributes:
      label: Operating System
      description: The OS you were using when this bug was encountered.
      options:
        - "Windows"
        - "Linux"
        - "Other (Windows Vsersion of GD)"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How to reproduce the crash.
      placeholder: "Example: 1) I did X..."
    validations:
      required: true
  - type: textarea
    id: crash-report
    attributes:
      label: Crash Report
      description: "You can find the crash report in `geode/crashlogs/`, if one was created. Additionally, please attach latest log in `geode/log/`. If either or both files do not exist, state such. Please link to a paste site with their content, such as GitHub Gists or Pastebin. **Do not paste the contents of either these files directly into the text box.**"
      placeholder: "Example: a link to a paste site with the crash report and latest.log."
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any additional information you wish to provide. Please add anything which did not fit into the other sections here.
      placeholder: "Example: This is likely caused by X because..."
    validations:
      required: false
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out this crash report.
