name: Request a Feature
description: Request a new feature or a change to an existing one.
labels: [ "feature" ]
body:
  - type: input
    id: version
    attributes:
      label: Version
      description: The version of GD Mod Hack you are using for suggesting a feature on.
      placeholder: "Example: v1.5.4"
    validations:
      required: false
  - type: textarea
    id: problem
    attributes:
      label: Requested Feature 
      description: The feature you want to request.
      placeholder: "Example: I'm want you to add X..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: How Will It Work?
      description: Describe how will it work with examples.
      placeholder: "Example: It works like..."
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any additional information you wish to provide. Please add anything which did not fit into the other sections here.
      placeholder: "Example: This is likely achievable by doing Z because..."
    validations:
      required: false
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out this feature request.
